insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (1, '36-5264171', 'Jade Plant', 'Badeau', '', true, 'Sudzha');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (2, '21-2483876', 'Cracked Lichen', 'Granby', null, false, 'Klippan');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (3, '40-1951413', 'Angularfruit Ma''oloa', 'Hintze', null, false, 'Banisilan');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (4, '72-7751619', 'Pine-leaf Bottlebrush', 'Fieldstone', null, true, 'Sucre');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (5, '63-7880876', 'Twayblade', 'Eastlawn', null, false, 'Takefu');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (6, '13-4214566', 'Talus Slope Bur Cucumber', 'Rigney', null, true, 'Silago');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (7, '22-3344533', 'Oneseed Bur Cucumber', 'Oxford', '', true, 'Calgary');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (8, '15-1695634', 'Acroceras', 'Tony', null, true, 'Krajan Dukuhseti');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (9, '61-2748517', 'Threadleaf Fleabane', 'Darwin', null, false, 'Getafe');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (10, '54-0317020', 'Rockbrake', 'Dorton', null, true, 'Maoyang');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (11, '64-6003529', 'Jopoy', 'Autumn Leaf', null, true, 'Municipio de Copacabana');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (12, '26-5588200', 'Risdon Peppermint Gum', 'Del Sol', null, false, 'Mantes-la-Jolie');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (13, '11-1518596', 'Jaffueliobryum Moss', 'Magdeline', null, false, 'Orléans');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (14, '11-7358463', 'Florist''s Daisy', 'Dottie', '', true, 'Waoundé');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (15, '39-0049173', 'Martinique Tonguefern', 'Wayridge', '', true, 'Woniuhe');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (16, '54-2487010', 'Scybalium', 'Lyons', '', true, 'Maroanging');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (17, '23-2120434', 'Kidney Lichen', 'Lillian', '', true, 'Lewograran');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (18, '12-2326825', 'Alpine Sulphur-flower Buckwheat', 'Elka', null, false, 'Stockton');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (19, '68-6481375', 'Monnina', '6th', '', true, 'Vista Hermosa');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (20, '69-3817048', 'Greater Burdock', 'Bartillon', null, true, 'Shilipu');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (21, '38-9957372', 'Indian Crabgrass', 'Northland', '', true, 'Shuangjie');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (22, '83-0317536', 'Muskeg Lousewort', 'Dryden', '', true, 'Gnieżdżewo');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (23, '68-3089165', 'Nut Palm', 'Huxley', '', true, 'Wonoharjo');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (24, '80-5842944', 'Exserted Indian Paintbrush', 'Di Loreto', '', false, 'Zverevo');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (25, '34-4014693', 'Black Bogrush', 'Nova', null, false, 'Sugihmukti');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (26, '48-3037299', 'Sedge', 'Nevada', null, true, 'Nagrak');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (27, '84-1136700', 'Canyon Creek Stonecrop', 'Warrior', null, false, 'Cabalawan');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (28, '70-7698584', 'Cusick''s Speedwell', 'Green Ridge', null, true, 'Magisterial');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (29, '02-8422524', 'Stemmy Four-nerve Daisy', 'Waubesa', '', true, 'Uzlovaya');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (30, '63-3848484', 'Almex', 'Graceland', null, true, 'Lamalewo');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (31, '13-4695768', 'Prairie Sedge', 'Carpenter', '', false, 'Muarasiau');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (32, '28-3195400', 'Pink', 'Toban', '', true, 'Guararé');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (33, '58-2354865', 'Pachyphiale Lichen', 'American Ash', null, true, 'Susiec');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (34, '52-1638961', 'Arburua Ranch Jewelflower', 'Ohio', '', true, 'Nonsan');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (35, '29-9674206', 'Oahu Melicope', 'Brickson Park', '', false, 'Oepuah');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (36, '55-4462121', 'Degelia Lichen', 'Burning Wood', null, false, 'Baro Kunda');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (37, '79-5779926', 'Nantucket Blackberry', 'Luster', null, false, 'La Foa');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (38, '41-7292362', 'Hassler''s Alternanthera', 'Melvin', null, false, 'Limbi');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (39, '92-9546820', 'Quillwort', 'Anzinger', null, false, 'Áyios Vasílios');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (40, '54-7135722', 'Hedge False Bindweed', 'Melody', null, false, 'Tenggong');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (41, '71-8105748', 'Yellow Water Buttercup', 'Clyde Gallagher', null, false, 'Mazeikiai');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (42, '75-8328044', 'Bog Rosemary', 'Sloan', null, true, 'União dos Palmares');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (43, '10-9071469', 'Arrowleaf Tearthumb', '6th', null, false, 'Reshui');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (44, '05-4488476', 'Starhorn', 'Nevada', '', true, 'Salamá');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (45, '27-2755580', 'Lobelia', 'Dakota', null, false, 'Kunsan');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (46, '67-5218470', 'Stinking Brickellbush', 'Fairview', null, false, 'Nova Viçosa');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (47, '26-8108301', 'Climbing Dogbane', 'Hudson', null, false, 'Shalakusha');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (48, '62-3654545', 'Tall Bluebells', 'Sunfield', null, true, 'Mouzáki');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (49, '63-5118927', 'Cabbage Gum', 'Annamark', '', false, 'Fenglai');
insert into property (id, user_id, name, adress, img_url, isProfileVisible, city) values (50, '27-3323555', 'Wedgeleaf Draba', 'Moland', '', false, 'Karangtengah');
